### ISSUE TITLE
Panic when trying to add labels via elemental-operator when no labels exist

### ISSUE THREAD

**Issue by agracey** [rancher/elemental-operator#92]
If I register a machine and don't specify any labels to add at creation time, future calls to `elemental-operator register --label "mykey=myval"` hang. If I look at the logs in the operator, I see: 

```
2022/07/27 19:44:52 http: panic serving pipe: assignment to entry in nil map
goroutine 1585 [running]:
net/http.(*conn).serve.func1()
        /usr/local/go/src/net/http/server.go:1802 +0xb9
panic({0x1b1a3e0, 0x20359e0})
        /usr/local/go/src/runtime/panic.go:1047 +0x266
github.com/rancher/elemental-operator/pkg/server.(*InventoryServer).ServeHTTP(0xc0016cd100, {0x2071e70, 0xc000988000}, 0x2032db8)
        /src/pkg/server/register.go:88 +0x55e
github.com/rancher/steve/pkg/auth.ToMiddleware.func1.1({0x2071e70, 0xc000988000}, 0xc00063d300)
        /go/pkg/mod/github.com/rancher/steve@v0.0.0-20220503004032-53511a06ff37/pkg/auth/filter.go:167 +0x3d4
net/http.HandlerFunc.ServeHTTP(0x0, {0x2071e70, 0xc000988000}, 0x464b8e)
        /usr/local/go/src/net/http/server.go:2047 +0x2f
net/http.serverHandler.ServeHTTP({0xc002732630}, {0x2071e70, 0xc000988000}, 0xc00063d300)
        /usr/local/go/src/net/http/server.go:2879 +0x43b
net/http.(*conn).serve(0xc0009280a0, {0x207a700, 0xc001d59440})
        /usr/local/go/src/net/http/server.go:1930 +0xb08
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:3034 +0x4e8
```

It looks like we need to check for nil at https://github.com/rancher/elemental-operator/blob/main/pkg/server/register.go#L81

**Comment by agracey** [comment]
The workaround for this is to make sure that the machineregistration has 
```
spec:
...
  machineInventoryLabels:
    somekey: someval
...
```
